user nginx;
worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 4096;
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 60s;
    server_tokens off;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        # DITO: Naka-listen sa 8081 (Internal)
        listen 80 default_server;
        server_name _;

        location = /health { return 200 "OK"; }
        location / { root /usr/local/openresty/index/html; try_files $uri $uri/ /index.html; }

        # Generic proxy template para sa lahat ng locations
        location ~ ^/(julpone|vmess|vless|ss) {
            proxy_pass http://127.0.0.1:10000; # Siguraduhin na tumuturo sa tamang xray port
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 3600s;
            proxy_buffering off;
        }
    }
}
