[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[program:xray]
command=/usr/bin/panares -config /etc/xray/config.json
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:haproxy]
command=/usr/local/sbin/haproxy -f /usr/local/etc/haproxy/haproxy.cfg -db
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
