name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main # Tatakbo ito tuwing mag-e-edit ka sa GitHub mo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Inayos mula sa DOCKERHUB_USERNAME
          password: ${{ secrets.DOCKER_PASSWORD }} # Inayos mula sa DOCKERHUB_TOKEN

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Direkta nating isulat ang username mo para siguradong walang error sa tag
          tags: julponefreenets/julpone-freenets:latest 
